PlanCurso:
    type: entity
    table: plan_curso
    indexes:
        IDX_999D051080E812A6:
            columns:
                - id_asignacion
    id:
        idPlan:
            type: bigint
            nullable: false
            unsigned: false
            id: true
            column: id_plan
            generator:
                strategy: SEQUENCE
    fields:
        sesion:
            type: integer
            nullable: false
            unsigned: false
        trabajoDirigido:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: trabajo_dirigido
        trabajoIndependienteDirigido:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: trabajo_independiente_dirigido
        trabajoIndependiente:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: trabajo_independiente
    manyToOne:
        idAsignacion:
            targetEntity: Asignacion
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_asignacion:
                    referencedColumnName: id_asignacion
            orphanRemoval: false
    lifecycleCallbacks: {  }
