'Uniajc\sgdepBundle\Entity\"accion"':
    type: entity
    table: '"Accion"'
    indexes:
        IDX_8DAEE682FCA5BA52:
            columns:
                - id_informacion
    id:
        idAccion:
            type: bigint
            nullable: false
            unsigned: false
            id: true
            column: id_accion
            generator:
                strategy: SEQUENCE
    fields:
        accion:
            type: string
            nullable: false
            length: 255
            fixed: false
    manyToOne:
        idInformacion:
            targetEntity: InformacionAsignatura
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_informacion:
                    referencedColumnName: id_informacion
            orphanRemoval: false
    lifecycleCallbacks: {  }
