'Uniajc\sgdepBundle\Entity\"aspectoEvaluacion"':
    type: entity
    table: '"Aspecto_evaluacion"'
    indexes:
        IDX_AD231014FCA5BA52:
            columns:
                - id_informacion
    id:
        idAspectoEvaluacion:
            type: bigint
            nullable: false
            unsigned: false
            id: true
            column: id_aspecto_evaluacion
            generator:
                strategy: SEQUENCE
    fields:
        aspectoEvaluacion:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: aspecto_evaluacion
    manyToOne:
        idInformacion:
            targetEntity: InformacionAsignatura
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_informacion:
                    referencedColumnName: id_informacion
            orphanRemoval: false
    lifecycleCallbacks: {  }
