'Uniajc\sgdepBundle\Entity\"aspectoMetodologico"':
    type: entity
    table: '"Aspecto_metodologico"'
    indexes:
        IDX_76CCADEAFCA5BA52:
            columns:
                - id_informacion
    id:
        idAspectoMetodologico:
            type: bigint
            nullable: false
            unsigned: false
            id: true
            column: id_aspecto_metodologico
            generator:
                strategy: SEQUENCE
    fields:
        aspectoMetodologico:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: aspecto_metodologico
    manyToOne:
        idInformacion:
            targetEntity: InformacionAsignatura
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_informacion:
                    referencedColumnName: id_informacion
            orphanRemoval: false
    lifecycleCallbacks: {  }
