Uniajc\sgdepBundle\Entity\AreaFormacion:
    type: entity
    table: area_formacion
    id:
        idArea:
            type: bigint
            nullable: false
            unsigned: false
            id: true
            column: id_area
            generator:
                strategy: SEQUENCE
    fields:
        nombre:
            type: string
            nullable: false
            length: 255
            fixed: false
        estado:
            type: smallint
            nullable: false
            unsigned: false
    lifecycleCallbacks: {  }
