uniajcsgdep_consulta:
    path:     /consulta/{tabla}/{campo}/{id}
    defaults: { _controller: UniajcsgdepBundle:Consulta:show }
uniajcsgdep_auth:
    path:     /auth
    defaults: { _controller: UniajcsgdepBundle:Auth:show }
    methods:  [POST]
    
uniajcsgdep_asignacion_consulta_docente:
    path:     /asignacion/{id_asignatura}/{sesion}/{rol}
    defaults: { _controller: UniajcsgdepBundle:Asignacion:show }
uniajcsgdep_asignacion_save_vocero:
    path:     /guarda/vocero/
    defaults: { _controller: UniajcsgdepBundle:Asignacion:saveVocero }
    methods:  [POST]
uniajcsgdep_asignacion_save_docente:
    path:     /guarda/docente/
    defaults: { _controller: UniajcsgdepBundle:Asignacion:saveDocente }
    methods:  [POST]
uniajcsgdep_asignacion_save_director:
    path:     /guarda/director/
    defaults: { _controller: UniajcsgdepBundle:Asignacion:saveDirector }
    methods:  [POST]
uniajcsgdep_materias_sesiones_reporte:
    path:     /materias/sesiones/reporte/{materia}
    defaults: { _controller: UniajcsgdepBundle:Asignacion:loadSesionesReporte }

uniajcsgdep_materias_docente:
    path:     /materias/docente/{id_docente}
    defaults: { _controller: UniajcsgdepBundle:Materias:loadDocente }
uniajcsgdep_materias_vocero:
    path:     /materias/vocero/{id_vocero}
    defaults: { _controller: UniajcsgdepBundle:Materias:loadVocero }
uniajcsgdep_materias_vocero:
    path:     /materias/director/{id_director}
    defaults: { _controller: UniajcsgdepBundle:Materias:loadDirector }
uniajcsgdep_materias_sesiones:
    path:     /materias/sesiones/{materia}
    defaults: { _controller: UniajcsgdepBundle:Materias:loadSesiones }
uniajcsgdep_materias_temas:
    path:     /materias/temas/{materia}/{sesion}
    defaults: { _controller: UniajcsgdepBundle:Materias:loadTemas }
uniajcsgdep_materias_temas_all:
    path:     /materias/temas_all/{materia}
    defaults: { _controller: UniajcsgdepBundle:Materias:loadAllTemas }
uniajcsgdep_materias_sesiones_mail:
    path:     /materias/sesiones/mail/
    defaults: { _controller: UniajcsgdepBundle:Materias:loadMailDocentes }